package com.example.telegram_api.enums;

public enum States {
    CONVERSATION_STARTED,
    WAITING_FOR_MAIL,
    WAITING_FOR_PASSWORD,
    SUCCESSFULLY_SIGNED_UP,
    ACTIVATED,
    ERROR,
    SUCCESSFULLY_LOGIN,
    LOGIN_WAIT_PASSWORD,
    WAITING_FOR_TICKER,
    ALERT_MENU,
    ALL_ALERTS,
    PLACE_ALERT,
    WAITING_FOR_PRICE,
    CLEARED_ALERTS,
    ALERT_MANAGEMENT
}